### ISSUE TITLE
Does the Outlook Web link work on mobile (iOS)?

### ISSUE THREAD

**Issue by jaredlt** [InteractionDesignFoundation/add-event-to-calendar-docs#16]
Have you been able to get the Outlook Web links to work on iOS?

The [test event link](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/outlook-web.md) works fine on desktop, but on iOS it simply takes me to the calendar page (not the add event page). I would expect it to open the Outlook app if it's available, or otherwise just render the web view for 'Add event' with the details populated, but it doesn't seem to work. Has this worked for you? Or is this simply behaviour that Microsoft have yet to implement? If the later, are you working around this in some way for any of your projects?

**Comment by alies-dev** [comment]
@jaredlt 
You can try to use this base URL: `https://outlook.office.com/calendar/0/deeplink/compose`


I found it here: https://github.com/AnandChowdhary/calendar-link/blob/master/src/index.ts

**Comment by jaredlt** [comment]
@alies-dev the `0` in that URL determines which user's account to use if the user is logged in to multiple Outlook accounts (`0` means use the first account, as opposed to `1` being the second account etc).

Upon re-testing the original [example link](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/outlook-web.md) it seems to work now! 🥳 I guess Microsoft fixed / implemented something in the last few years. Thanks for checking back in here.
