### ISSUE TITLE
Ampersand in Subject for Outlook Web renders as &amp;

### ISSUE THREAD

**Issue by jaredlt** [InteractionDesignFoundation/add-event-to-calendar-docs#17]
When I pass a Subject with an ampersand, it displays as `&amp;`

Eg. `Birthday & Sleepover` percent-encoded to: `&subject=Birthday%20%26%20Sleepover`

[Test link](https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-12-31T19:30:00Z&enddt=2020-12-31T22:30:00Z&subject=Birthday%20%26%20Sleepover&body=With%20clowns%20and%20stuff&location=North%20Pole)

![image](https://user-images.githubusercontent.com/8590311/86272129-fca75e80-bbc5-11ea-899c-b4d2af892012.png)

This seems like a bug on Microsoft's side, but I wonder if you know of any hack that might get around it?

**Comment by lptn** [comment]
this is what they use:

```ts
if (params[SUBJECT_QUERYSTRING_KEY]) {
    event.Subject = HtmlSanitizer.sanitizeHtml(params[SUBJECT_QUERYSTRING_KEY]);
}
```

I assume there is no way to bypass it :/

**Comment by jaredlt** [comment]
@lptn Thanks for your speedy response! :) 

It's weird as ampersands work fine in their Body (you'd think they'd use the same sanitizer everywhere...) 🤷‍♂️ 

I think I will detect and replace `&` with `and` in my gem (just for Outlook Web's Subject), as a workaround.
