### ISSUE TITLE
Outlook showing wrong time for events on mobile

### ISSUE THREAD

**Issue by bobeagan** [InteractionDesignFoundation/add-event-to-calendar-docs#21]
Using this example link: https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-12-31T19:30:00Z&enddt=2020-12-31T22:30:00Z&subject=Birthday&body=With%20clowns%20and%20stuff&location=North%20Pole

Will show correctly on desktop but using the same link in iOS (but I'm told this also is a problem on Android) will fail to pick up the correct times. I've tried manipulating the time format in many different ways to get it to pick up without luck. 

If I try an event that spams multiple days, using an example like this: https://outlook.live.com/calendar/0/deeplink/compose?startdt=2020-08-12T00:00:00&enddt=2020-08-13T12:00:00&subject=Hello%20World&body=Hello%20World

The end time is correct but the start time is still wrong. From what I can gather it appears to be rounding up to the nearest hour for the start time.

Wondering if anyone else can reproduce this and/or has figured out a workaround for this to work on mobile.

**Comment by HiteshMali1711** [comment]
![image](https://user-images.githubusercontent.com/81588226/114175391-d8b04080-98ee-11eb-824f-142658bb8acb.png)

I can see this error in console when we try to open outlook calendar link

**Comment by parap** [comment]
I guess it has something in common with force-setting time to have UTC timezone in `WebOutlook->generate()`. Have the same issue -- outlook calendar generates wrong time.

`Google->generate()` doesn't force the same date to UTC and produces correct date.

**Comment by soplan** [comment]
We are also experiencing the same issue. Haven't figured out how to fix this for mobile.

Any suggestions or work arounds are welcome!

**Comment by Tsjippy** [comment]
Same issue here!

**Comment by strewhella** [comment]
Seeing this too. [The test event](https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-12-31T19:30:00Z&enddt=2020-12-31T22:30:00Z&subject=Birthday&body=With%20clowns%20and%20stuff&location=North%20Pole) shows 12pm -> 12:30pm on mobile instead of 6:30am -> 9:30am

**Comment by HagarAyad** [comment]
Same issue here! , anyone found a solution?

**Comment by jesusPoveda** [comment]
This still happening, outlook desktop and web will pick up the right time , but for mobile devices wont

**Comment by jekuer** [comment]
This seems to be resolved by Microsoft.
**Works now as expected.**

**Comment by lptn** [comment]
>Works now as expected.

cool, closing the issue then 👍
