### ISSUE TITLE
Yahoo URL does not work

### ISSUE THREAD

**Issue by nowackimvn** [InteractionDesignFoundation/add-event-to-calendar-docs#22]
Yahoo link does not work. Opens a blank calendar lightbox.

**Comment by fras2560** [comment]
@nowackimvn were you able to resolve this issue?

I get the same behavior but it seems to be account dependent. I made a new yahoo account that works correctly but a co-worker made one that gets blank calendar.

The only difference I can think it the code worker is in Eastern Europe where as I am in North America. If anyone has more insight into this that would be appreciated.

**Comment by thedeephakani** [comment]
it's working a few days back, but now I am facing the same issue. able to open the calendar. But all field has wrong value. 
I try with a sample URL. but it's also not working. 

[](https://calendar.yahoo.com/?v=60&title=Birthday&st=20201231T193000&et=20201231T223000&desc=With%20clowns%20and%20stuff&in_loc=North%20Pole&inv_list=John+Doe+%3Cjohn@example.com%3E,Jane+Doe+%3Cjane@example.com%3E)

![Screenshot from 2021-03-16 13-19-25](https://user-images.githubusercontent.com/62884815/111273825-4b186280-865a-11eb-9a99-fc5f78aa49e9.png)

**Comment by HiteshMali1711** [comment]
I managed to solve this issue. Looks like prams which we are passing are really case sensitive. I used TITLE,ST and ET all in caps and it worked for me 
![image](https://user-images.githubusercontent.com/81588226/112887862-84a09300-9088-11eb-953b-9a0e27ea2462.png)

**Comment by lptn** [comment]
@HiteshMali1711  Thanks a lot! I've updated yahoo doc: https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/commit/ff40cbb71ea7302dea6e67a2fc18eaa72c6c7722

Can you please also check other params?

**Comment by dmalan** [comment]
@HiteshMali1711, thanks for sharing! Though did you find that the UTC offset (`Z`) was preserved? I just tried, e.g.,

https://calendar.yahoo.com/?v=60&ST=20210330T200000Z&ET=20210330T210000Z&TITLE=test

which is intended to start at 2021-03-30 20:00:00 UTC (i.e., 2021-03-30 16:00:00 Eastern Time), which does populate Yahoo's UI with those times:

<img width="471" alt="Screen Shot 2021-03-29 at 4 14 58 PM" src="https://user-images.githubusercontent.com/788678/112894503-f3421880-90a9-11eb-8ed1-8d70027a6e69.png">

But the event ends up in my calendar as 2021-03-30 20:00:00 Eastern Time, which is four hours off. Even though my own calendar is configured to use Eastern Time:

<img width="714" alt="Screen Shot 2021-03-29 at 4 16 13 PM" src="https://user-images.githubusercontent.com/788678/112894674-24bae400-90aa-11eb-86a4-a456dab615a2.png">

If I export my calendar's .ics file, I see the incorrect times too:

```
BEGIN:VEVENT
SUMMARY:test
CLASS:PUBLIC
DTSTART;TZID=America/New_York:20210330T200000
DTEND;TZID=America/New_York:20210330T210000
...
```

I.e., even though the capitalized HTTP parameters help, it seems Yahoo still isn't handling the UTC offset (`Z`) correctly?
