### ISSUE TITLE
add event URL does not work

### ISSUE THREAD

**Issue by shufei173556** [InteractionDesignFoundation/add-event-to-calendar-docs#24]
[add event URL] unable to bring title and description and so on to event(as blow Screenshots), can you fix this issue or provide a new [add event URL]
![image](https://user-images.githubusercontent.com/26454422/110451444-2aeb1f80-80ff-11eb-9f46-ce3e2c61f2e3.png)

**Comment by lptn** [comment]
duplicate #22 ( Yahoo URL does not work)
