### ISSUE TITLE
Any way to add to iOS/Android

### ISSUE THREAD

**Issue by pkiula** [InteractionDesignFoundation/add-event-to-calendar-docs#6]
Thanks for this lovely info. How can I use one of these to create the ".ics" stuff for adding easily to mobile OS calendar? Many thanks.

**Comment by lptn** [comment]
@pkiula 
I hope if will help you: [What is a webcal protocol?](https://stackoverflow.com/questions/5603866/what-is-a-webcal-protocol)

**Comment by pkiula** [comment]
Thanks. I couldn’t find anything in that question or the Wikipedia link that they link to about how to compose the webcam URL for all these services. What’s the precise URL composition logic? Thanks.

**Comment by lptn** [comment]
@pkiula 
I think for your case you should to generate I link to download `.ics` file with `webcal:` pseudo-protocol.

But... I'm sorry, this repo is out of scope of .ics files.

**Comment by AnandChowdhary** [comment]
More context: If you just download an `ICS` file, all iOS, iPadOS, and Android will take you to the default calendar app and open the file. You should just use an ICAL generator.

You can also use which also generates the ICS file: https://github.com/AnandChowdhary/add-to-calendar
