### ISSUE TITLE
Yahoo `et` parameter has doesn't work

### ISSUE THREAD

**Issue by dsbudiac** [InteractionDesignFoundation/add-event-to-calendar-docs#7]
Use `dur` instead.

See: https://stackoverflow.com/questions/20238235/link-for-sharing-an-event-to-yahoo-calendar#comment54120394_28036433

**Comment by lptn** [comment]
thanks @dsbudiac , I just added a note about that: https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/commit/c1e8981f6b1899454864b32879b8df13f736b53e
